18 game engine basic architecture
etib-corp/r-type pull request #47
Opened 2024-09-19 12:41 UTC by ju-lit-hein

2024-09-19 12:46 UTC, MAILLOTNathan requested changes

2024-09-19 12:46 UTC, MAILLOTNathan commented on client/include/EventManager.hpp
Don't forget to document that

2024-09-19 13:47 UTC, ju-lit-hein commented on client/include/EventManager.hpp
Ok i did it.

2024-09-19 14:43 UTC, ElPepitaux approved these changes

2024-09-20 10:06 UTC, MAILLOTNathan approved these changes

2024-09-21 05:06 UTC, merged