6 game physics
etib-corp/r-type pull request #85
Opened 2024-09-30 13:29 UTC by ju-lit-hein

2024-09-30 14:39 UTC, MAILLOTNathan requested changes

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/BoxComponent.hpp
Document that

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/HitBoxComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/HurtBoxComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/ModelComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/MotionComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Components/SpriteComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Systems/Render2DSystem.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on client/include/ECS/Systems/Render3DSystem.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on include/ECS/Components/HealthComponent.hpp
Same

2024-09-30 14:39 UTC, MAILLOTNathan commented on include/ECS/Components/TransformComponent.hpp
Same

2024-10-01 13:29 UTC, ju-lit-hein commented on client/include/ECS/Components/BoxComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:29 UTC, ju-lit-hein commented on client/include/ECS/Components/HitBoxComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:29 UTC, ju-lit-hein commented on client/include/ECS/Components/HurtBoxComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on include/ECS/Components/TransformComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on include/ECS/Components/HealthComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on client/include/ECS/Systems/Render3DSystem.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on client/include/ECS/Systems/Render2DSystem.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on client/include/ECS/Components/SpriteComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on client/include/ECS/Components/MotionComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 13:31 UTC, ju-lit-hein commented on client/include/ECS/Components/ModelComponent.hpp
I documented it @MAILLOTNathan

2024-10-01 14:22 UTC, ju-lit-hein commented
Please do not close the branch after merging it into main @MAILLOTNathan

2024-10-01 16:06 UTC, merged